name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - name : "Check out repository code"
        uses: actions/checkout@v4.1.1        
      - run: |
          sudo apt-get update
          sudo apt-get install --yes cowsay
      - run: cat README.md | cowsay
      - run: ls -l # Liste les fichier du répertoire courant
      - run: cat README.md | cowsay dans GitPod # pipe le contenu du fichier `README.md` dans cowsay